### ISSUE TITLE
Crafting

### ISSUE THREAD

**Issue by 8mcgraw** [8mcgraw/TowerDefense#3]
Using resources to get building pieces - like tower base or tower orb. Develop crafting system and requirements, answer questions like: Do we want to need resources from enemies? Will we have a crafting or smithing table? Will it require in game time to craft?

**Comment by Talloy-ux** [comment]
Resources are from underground block types; Crafting location is a collider trigger to tell the player what to press if they have the resources to get a tower; Instant crafting time as resources gathering and fighting enemies happens simultaneously.
